### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by rubyFeedback** [natorsc/python-gtk-pygobject#11]
Would it be possible to add examples + comments in english?

I am not necessarily saying to rewrite all examples, but perhaps
a special directory with examples in raw english. That may help
more people find the repository too, by the way. Right now there
is a lack of python-gtk4 stuff (ruby-gtk4 even more so).

**Comment by natorsc** [comment]
Hi @rubyFeedback.

I recently added the sphinx library to structure content in more than one language.

I should start the translation soon.

**Comment by natorsc** [comment]
Added README.md in English.
